mkdir tsfresh
python pre_tsfresh_minimal.py -d ACSF1
python pre_tsfresh_minimal.py -d DodgerLoopGame
python pre_tsfresh_minimal.py -d GunPointAgeSpan
python pre_tsfresh_minimal.py -d MoteStrain
python pre_tsfresh_minimal.py -d SmallKitchenAppliances
python pre_tsfresh_minimal.py -d Adiac
python pre_tsfresh_minimal.py -d DodgerLoopWeekend
python pre_tsfresh_minimal.py -d GunPointMaleVersusFemale
python pre_tsfresh_minimal.py -d NonInvasiveFetalECGThorax1
python pre_tsfresh_minimal.py -d SmoothSubspace
python pre_tsfresh_minimal.py -d AllGestureWiimoteX
python pre_tsfresh_minimal.py -d Earthquakes
python pre_tsfresh_minimal.py -d GunPointOldVersusYoung
python pre_tsfresh_minimal.py -d NonInvasiveFetalECGThorax2
python pre_tsfresh_minimal.py -d SonyAIBORobotSurface1
python pre_tsfresh_minimal.py -d AllGestureWiimoteY
python pre_tsfresh_minimal.py -d ECG200
python pre_tsfresh_minimal.py -d Ham
python pre_tsfresh_minimal.py -d OliveOil
python pre_tsfresh_minimal.py -d SonyAIBORobotSurface2
python pre_tsfresh_minimal.py -d AllGestureWiimoteZ
python pre_tsfresh_minimal.py -d ECG5000
python pre_tsfresh_minimal.py -d HandOutlines
python pre_tsfresh_minimal.py -d OSULeaf
python pre_tsfresh_minimal.py -d ArrowHead
python pre_tsfresh_minimal.py -d ECGFiveDays
python pre_tsfresh_minimal.py -d Haptics
python pre_tsfresh_minimal.py -d PhalangesOutlinesCorrect
python pre_tsfresh_minimal.py -d Strawberry
python pre_tsfresh_minimal.py -d Beef
python pre_tsfresh_minimal.py -d ElectricDevices
python pre_tsfresh_minimal.py -d Herring
python pre_tsfresh_minimal.py -d Phoneme
python pre_tsfresh_minimal.py -d SwedishLeaf
python pre_tsfresh_minimal.py -d BeetleFly
python pre_tsfresh_minimal.py -d EOGHorizontalSignal
python pre_tsfresh_minimal.py -d HouseTwenty
python pre_tsfresh_minimal.py -d PickupGestureWiimoteZ
python pre_tsfresh_minimal.py -d Symbols
python pre_tsfresh_minimal.py -d BirdChicken
python pre_tsfresh_minimal.py -d EOGVerticalSignal
python pre_tsfresh_minimal.py -d InlineSkate
python pre_tsfresh_minimal.py -d PigAirwayPressure
python pre_tsfresh_minimal.py -d SyntheticControl
python pre_tsfresh_minimal.py -d BME
python pre_tsfresh_minimal.py -d EthanolLevel
python pre_tsfresh_minimal.py -d InsectEPGRegularTrain
python pre_tsfresh_minimal.py -d PigArtPressure
python pre_tsfresh_minimal.py -d ToeSegmentation1
python pre_tsfresh_minimal.py -d Car
python pre_tsfresh_minimal.py -d FaceAll
python pre_tsfresh_minimal.py -d InsectEPGSmallTrain
python pre_tsfresh_minimal.py -d PigCVP
python pre_tsfresh_minimal.py -d ToeSegmentation2
python pre_tsfresh_minimal.py -d CBF
python pre_tsfresh_minimal.py -d FaceFour
python pre_tsfresh_minimal.py -d InsectWingbeatSound
python pre_tsfresh_minimal.py -d PLAID
python pre_tsfresh_minimal.py -d Trace
python pre_tsfresh_minimal.py -d Chinatown
python pre_tsfresh_minimal.py -d FacesUCR
python pre_tsfresh_minimal.py -d ItalyPowerDemand
python pre_tsfresh_minimal.py -d Plane
python pre_tsfresh_minimal.py -d TwoLeadECG
python pre_tsfresh_minimal.py -d ChlorineConcentration
python pre_tsfresh_minimal.py -d FiftyWords
python pre_tsfresh_minimal.py -d LargeKitchenAppliances
python pre_tsfresh_minimal.py -d PowerCons
python pre_tsfresh_minimal.py -d TwoPatterns
python pre_tsfresh_minimal.py -d CinCECGTorso
python pre_tsfresh_minimal.py -d Fish
python pre_tsfresh_minimal.py -d Lightning2
python pre_tsfresh_minimal.py -d ProximalPhalanxOutlineAgeGroup
python pre_tsfresh_minimal.py -d UMD
python pre_tsfresh_minimal.py -d Coffee
python pre_tsfresh_minimal.py -d FordA
python pre_tsfresh_minimal.py -d Lightning7
python pre_tsfresh_minimal.py -d ProximalPhalanxOutlineCorrect
python pre_tsfresh_minimal.py -d UWaveGestureLibraryAll
python pre_tsfresh_minimal.py -d Computers
python pre_tsfresh_minimal.py -d FordB
python pre_tsfresh_minimal.py -d Mallat
python pre_tsfresh_minimal.py -d ProximalPhalanxTW
python pre_tsfresh_minimal.py -d UWaveGestureLibraryX
python pre_tsfresh_minimal.py -d CricketX
python pre_tsfresh_minimal.py -d FreezerRegularTrain
python pre_tsfresh_minimal.py -d Meat
python pre_tsfresh_minimal.py -d RefrigerationDevices
python pre_tsfresh_minimal.py -d UWaveGestureLibraryY
python pre_tsfresh_minimal.py -d CricketY
python pre_tsfresh_minimal.py -d FreezerSmallTrain
python pre_tsfresh_minimal.py -d MedicalImages
python pre_tsfresh_minimal.py -d Rock
python pre_tsfresh_minimal.py -d UWaveGestureLibraryZ
python pre_tsfresh_minimal.py -d CricketZ
python pre_tsfresh_minimal.py -d Fungi
python pre_tsfresh_minimal.py -d MelbournePedestrian
python pre_tsfresh_minimal.py -d ScreenType
python pre_tsfresh_minimal.py -d Wafer
python pre_tsfresh_minimal.py -d Crop
python pre_tsfresh_minimal.py -d MiddlePhalanxOutlineAgeGroup
python pre_tsfresh_minimal.py -d SemgHandGenderCh2
python pre_tsfresh_minimal.py -d Wine
python pre_tsfresh_minimal.py -d DiatomSizeReduction
python pre_tsfresh_minimal.py -d GestureMidAirD2
python pre_tsfresh_minimal.py -d MiddlePhalanxOutlineCorrect
python pre_tsfresh_minimal.py -d SemgHandMovementCh2
python pre_tsfresh_minimal.py -d WordSynonyms
python pre_tsfresh_minimal.py -d DistalPhalanxOutlineAgeGroup
python pre_tsfresh_minimal.py -d GestureMidAirD3
python pre_tsfresh_minimal.py -d MiddlePhalanxTW
python pre_tsfresh_minimal.py -d SemgHandSubjectCh2
python pre_tsfresh_minimal.py -d Worms
python pre_tsfresh_minimal.py -d DistalPhalanxOutlineCorrect
python pre_tsfresh_minimal.py -d GesturePebbleZ1
python pre_tsfresh_minimal.py -d ShakeGestureWiimoteZ
python pre_tsfresh_minimal.py -d WormsTwoClass
python pre_tsfresh_minimal.py -d DistalPhalanxTW
python pre_tsfresh_minimal.py -d GesturePebbleZ2
python pre_tsfresh_minimal.py -d MixedShapesRegularTrain
python pre_tsfresh_minimal.py -d ShapeletSim
python pre_tsfresh_minimal.py -d Yoga
python pre_tsfresh_minimal.py -d DodgerLoopDay
python pre_tsfresh_minimal.py -d GunPoint
python pre_tsfresh_minimal.py -d MixedShapesSmallTrain
python pre_tsfresh_minimal.py -d ShapesAll
python pre_tsfresh_minimal.py -d StarLightCurves
python pre_tsfresh_minimal.py -d GestureMidAirD1
